### ISSUE TITLE
Help with .NET Standard

### ISSUE THREAD

**Issue by Mike-EEE** [nreco/lambdaparser#1]
I am upgrading my nugets to .NET Standard, and while upgrading NReco.LambdaParser in my .NET 4.6.1 projects, I get the following error:

```
Failed to add reference. The package 'NReco.LambdaParser' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
```

Is this a known issue, by chance?

**Comment by VitaliyMF** [comment]
@Mike-EEE I was able to reproduce the same error with empty console app that targets 4.6.1. It seems this is known Nuget issue ( https://github.com/NuGet/Home/issues/3103, https://github.com/NuGet/Home/issues/2193 ).

As I understand when nuget installs NReco.LambdaParser package, it correctly chooses  netstandard1.3 build, but for some unknown reason tries to resolve (in absolutely incorrect way) dependencies from PCL45-build. Until this bug fixed, workaround is marking framework assembly dependencies as build-time, like `"System.Collections": { "type": "build" }`.

I'm going to rebuild nuget package with these changes and check if this helps.

**Comment by VitaliyMF** [comment]
Just published NReco.LambdaParser 1.0.3 with patched framework dependencies configuration for portable builds; I've tried to install it for the following targets:  .NET 4.0, .NET 4.5.1, .NET 4.6.1, .NET Core App, and now package is installed correctly.

**Comment by Mike-EEE** [comment]
Success!  Thank you so much!
