### ISSUE TITLE
can be support = and == both pattern?

### ISSUE THREAD

**Issue by akaylh** [nreco/lambdaparser#13]
For example, a=b and a==b, the effect on both is the same.

**Comment by VitaliyMF** [comment]
Yes, it is possible to handle 'a=b' in the same way as 'a==b'.
However, this may be undesired in some cases, and it is better to have special option to enable this behavior (only when needed).

**Comment by VitaliyMF** [comment]
Added `LambdaParser.AllowSingleEqualSign` property to enable equal comparison with single sign.

Shipped in 1.0.9

**Comment by akaylh** [comment]
Is great, thank you very much.
