### ISSUE TITLE
null in expression evaluated as variable

### ISSUE THREAD

**Issue by fromberg100** [nreco/lambdaparser#2]
Hi,

first of all thank you for you project.  It is helping a lot in a project I am working on.

There is an issue when I use null to evaluate a boolean expression, for example:

20 == null

In this case, null is considered a variable and it is expected on the values dictionary.

The workaround I am using is:
values["null"] = null;

Thanks again and regards,

**Comment by VitaliyMF** [comment]
Fixed in 1.0.4 (already published on nuget.org - you may upgrade your reference).
